---
- name: start certificate manager deployment
  k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: '{{ meta.name }}-certificate-manager'
        namespace: '{{ meta.namespace }}'
      spec:
        selector:
          matchLabels:
            app: '{{ meta.name }}-certificate-manager'
        template:
          metadata:
            labels:
              app: '{{ meta.name }}-certificate-manager'
          spec:
            imagePullSecrets: 
            - name: dw-engine-image-pull-secret
            containers:
            - name: certificate-manager
              image: '{{ certificate_manager_image }}'
              resources:
                limits:
                  memory: '{{ certificate_manager_mem_limit }}'
                  cpu: '{{ certificate_manager_cpu_limit }}'
              env:
                - name: AMQP_URL
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-rabbitmq-secret'
                      key: url
                - name: CERTIFICATE_EXCHANGE
                  value: certificate-exchange
                - name: CERTIFICATE_QUEUE
                  value: certificate-queue
                - name: COG_EXCHANGE
                  value: cog-exchange
                - name: COG_QUEUE
                  value: cog-queue
                - name: DEAD_LETTER_EXCHANGE
                  value: dl-certificate-exchange
                - name: DEAD_LETTER_QUEUE
                  value: dl-certificate-queue
                - name: QUEUE_RETRY_QTY
                  value: "3"
                - name: CERT_DB_USER
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-mongodb-configuration'
                      key: username
                - name: CERT_DB_PASSWORD
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-mongodb-configuration'
                      key: password
                - name: CERT_DB_HOST
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-mongodb-configuration'
                      key: host
                - name: CERT_DB_PORT
                  value: "27017"
                - name: CERT_DB_DATABASE
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-mongodb-configuration'
                      key: database
