---
- name: start ontology manager deployment
  k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: '{{ meta.name }}-ontology-manager'
        namespace: '{{ meta.namespace }}'
      spec:
        selector:
          matchLabels:
            app: '{{ meta.name }}-ontology-manager'
        template:
          metadata:
            labels:
              app: '{{ meta.name }}-ontology-manager'
          spec:
            imagePullSecrets: 
            - name: dw-engine-image-pull-secret
            containers:
            - name: ontology-manager
              image: '{{ ontology_manager_image }}'
              resources:
                limits:
                  memory: '{{ ontology_manager_mem_limit }}'
                  cpu: '{{ ontology_manager_cpu_limit }}'
              env:
                - name: MESSAGES_PORT
                  value: "5672"
                - name: MESSAGES_HOST
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-rabbitmq-secret'
                      key: host
                - name: MESSAGES_USER
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-rabbitmq-secret'
                      key: username
                - name: MESSAGES_PASS
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-rabbitmq-secret'
                      key: password
                - name: MESSAGES_VHOST
                  value: lichen-engine
                - name: STORAGE_USER
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-mongodb-configuration'
                      key: username
                - name: STORAGE_PASS
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-mongodb-configuration'
                      key: password
                - name: STORAGE_HOST
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-mongodb-configuration'
                      key: host
                - name: STORAGE_PORT
                  value: "27017"
                - name: STORAGE_DB
                  value: payload-storage
                - name: REPORTS_USER
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-mongodb-configuration'
                      key: username
                - name: REPORTS_PASS
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-mongodb-configuration'
                      key: password
                - name: REPORTS_HOST
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-mongodb-configuration'
                      key: host
                - name: REPORTS_PORT
                  value: "27017"
                - name: REPORTS_DB
                  value: reports
