---
- name: start wkc-manager deployment
  k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: '{{ meta.name }}-wkc-manager'
        namespace: '{{ meta.namespace }}'
      spec:
        selector:
          matchLabels:
            app: '{{ meta.name }}-wkc-manager'
        template:
          metadata:
            labels:
              app: '{{ meta.name }}-wkc-manager'
          spec:
            imagePullSecrets: 
            - name: dw-engine-image-pull-secret
            containers:
            - name: 'wkc-manager'
              image: '{{ wkc_manager_image }}'
              resources:
                limits:
                  memory: '{{ wkc_manager_mem_limit }}'
                  cpu: '{{ wkc_manager_cpu_limit }}'
              command: ["python3"]
              args: ['main.py']
              env:
                - name: AMQP_HOST
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-rabbitmq-secret'
                      key: host
                - name: AMQP_PORT
                  value: "5672"
                - name: AMQP_VHOST
                  value: certificate-manager
                - name: AMQP_USER
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-rabbitmq-secret'
                      key: username
                - name: AMQP_PASSWORD
                  valueFrom: 
                    secretKeyRef:
                      name: '{{ meta.name }}-rabbitmq-secret'
                      key: password
                - name: COG_EXCHANGE
                  value: cog-exchange
                - name: COG_QUEUE
                  value: cog-queue
                - name: CERTIFICATE_EXCHANGE
                  value: certificate-exchange
                - name: CERTIFICATE_QUEUE
                  value: certificate-queue
                - name: DEAD_LETTER_EXCHANGE
                  value: dl-cog-exchange
                - name: DEAD_LETTER_QUEUE 
                  value: dl-cog-queue
                - name: QUEUE_RETRY_QTY
                  value: "3"
                - name: CP4D_URL
                  value: '{{ cp4d_url }}'
                - name: CP4D_USER
                  value: '{{ cp4d_user }}'
                - name: CP4D_PASSWORD
                  value: '{{ cp4d_password }}'
                - name: CP4D_API_KEY
                  value: '{{ cp4d_api_key }}'
